"""Leakage-safe demand forecasting, target weather, and evaluation contracts."""

from forecasting.baseline import (
    BacktestConfig,
    ForecastWeatherConfig,
    ForecastWeatherContractError,
    ForecastWeatherReconciliationConfig,
    ForecastWeatherReconciliationError,
    ForecastingContractError,
    RollingOriginFold,
    attach_target_forecast_weather,
    build_demo_feature_frame,
    build_demo_forecast_weather_frame,
    build_rolling_origin_folds,
    build_supervised_frame,
    prepare_feature_frame,
    prepare_forecast_reconciliation_input,
    prepare_forecast_weather_frame,
    prepare_observed_weather_input,
    prepare_weather_model_comparison,
    reconcile_forecast_weather,
    run_chronological_backtest,
    run_rolling_origin_backtest,
    run_weather_model_comparison,
)

__all__ = [
    "BacktestConfig",
    "ForecastWeatherConfig",
    "ForecastWeatherContractError",
    "ForecastWeatherReconciliationConfig",
    "ForecastWeatherReconciliationError",
    "ForecastingContractError",
    "RollingOriginFold",
    "attach_target_forecast_weather",
    "build_demo_feature_frame",
    "build_demo_forecast_weather_frame",
    "build_rolling_origin_folds",
    "build_supervised_frame",
    "prepare_feature_frame",
    "prepare_forecast_reconciliation_input",
    "prepare_forecast_weather_frame",
    "prepare_observed_weather_input",
    "prepare_weather_model_comparison",
    "reconcile_forecast_weather",
    "run_chronological_backtest",
    "run_rolling_origin_backtest",
    "run_weather_model_comparison",
]
